[package]
name = "randaam"
version = "0.1.3"
edition = "2021"
description = "Generate random imaginary people in all your rust projects"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
