[package]
name = "randaam-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
randaam = { version = "0.1.2", path = "../randaam" }
