use rand::seq::SliceRandom; // 0.7.2

pub fn name() -> String {
    let names = vec![
        "Harry",
        "Bert",
        "Henk",
        "Sebastiaan",
        "Papa",
        "Rutger",
        "Mama",
        "Lars",
        "Steven",
        "Jannes",
        "Iwan",
        "Milan",
        "Bertwim",
        "Amgela",
        "Jorgiam",
        "Hansje",
        "Pim",
        "Sandra",
        "Hennie",
        "Achmet",
        "Dirkjan",
        "Barbaba",
        "Jeroen",
        "Riejan",
        "Willem",
        "Leo",
        "Meneer",
        "Bas",
        "Dennis",
        "Jan",
        "Kees",
        "Lies",
        "Sem",
        "Jan",
        "Cor",
        "Lucas",
        "Finn",
        "Daan",
        "Levi",
        "Milan",
        "Bram",
        "Luuk",
        "Emma",
        "Tess",
        "Sophie",
        "Julia",
        "Anna",
        "Mila",
        "Sara",
        "Luuk",
        "Jesse",
        "Mees",
        "Thomas",
        "Sam",
        "Thijs",
        "Adam",
        "Max",
        "Jullian",
        "Hugo",
        "Gijs",
        "Benjamin",
        "Tim",
        "Ruben",
        "Teun",
        "Olivier",
        "Sven",
        "David",
        "Stijn",
        "Tom",
        "Isa",
        "Noa",
        "Jasmijn",
        "Esmee",
        "Sanne",
        "Joël",
        "Emmanuel",
        "Nathan",
        "Tobias",
        "Alex",
        "Daniële",
        "Elias",
        "Carlijn",
        "Caroline",
        "Lisanne",
        "Marije",
        "Tirza",
        "Naomi",
        "Joyce",
        "Indy",
        "Marith",
        "Micha",
        "Hayanne",
        "Isa",
        "Nadine",
        "Aron",
    ];

    // let vs = vec![0, 1, 2, 3, 4];
    // println!("{:?}", names.choose(&mut rand::thread_rng()));
    let result = names.choose(&mut rand::thread_rng()).unwrap().to_string();
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    pub fn test_name() {
        assert!(name().len() > 0);
    }
}
